apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eks-sample-linux-app
  name: eks-sample-deployment
  namespace: eks-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sample-linux-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eks-sample-linux-app
    spec:
      containers:
        - image: 486306523629.dkr.ecr.ap-southeast-1.amazonaws.com/spring-boot-eks:1.0-SNAPSHOT
          name: spring-boot-eks
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 80
status: {}

