apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wavesdev-cluster
  region: ap-southeast-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.micro
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: pranavan-admin
